config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index', as: "auth_root"
  end  
  root "welcome#index"



  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  

  def index
    @notes = Note.where(user_id: current_user).order(priority: :desc)
    @page_description = 'Page with all Notes'
  end
  
  def show
    @page_title = @note.htmltitle
    @page_description = @note.htmldescription
	end
  
  def new
    @note = current_user.notes.build
  end
  
  def create
    @note = current_user.notes.build(params_note)

    if @note.save
      redirect_to @note
    else
      render 'new'  
    end
  end
  
  def edit

  end
    
  def update
    if @note.update(params_note) 
      redirect_to @note
    else
      render 'edit'  
    end  
  end
  
  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private 

  def find_note
    @note=Note.find(params[:id])
  end

  def params_note
    params.require(:note).permit(:title, :content, :htmltitle, :htmldescription, :priority)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@page_description = 'Welcome Page'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  = display_meta_tags site: 'YourNoteBook | Leave Your Notes Online'
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
%body 
  %nav.navbar.navbar-default
    .container
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Add New Note", new_note_path
          %li= link_to "Log Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
    .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  =f.input :title,required: true, placeholder: 'Note Name'
  =f.input :content,required: true, placeholder: 'Your Note', as: :wysihtml5
  =f.input :htmltitle,required: true, placeholder: 'Note HTML Title'
  =f.input :htmldescription,required: true, placeholder: 'Note HTML Description'
  =f.input :priority, collection: 1..10, promt: 'Select priority', selected: 1
  =f.hidden_field :user_id, :value => current_user.id
  =f.button :submit

app/views/notes/edit.html.haml
.container
  .row
    .col-md-12
      %h1 Edit Note Page!
      = render 'form'
      = link_to 'Cancel', notes_path

app/views/notes/index.html.haml
.container
  .row
    .col-md-12
      %h1.glyphicon.glyphicon-list-alt All Your Notes
  .row
  - @notes.each do |note|
    .col-md-2
      %h2.glyphicon.glyphicon-tag= link_to note.title, note
      %p Passed: #{time_ago_in_words(note.created_at)}
      %p Priority: #{note.priority}

app/views/notes/new.html.haml
.container
  .row
    .col-md-12
      %h1 Add New Note
      = render 'form'
      = link_to 'Cancel', notes_path

app/views/notes/show.html.haml
- if (current_user.id == @note.user_id)
  .container
    .row
      .col-md-12
        %h1= @note.title
    .row
      .col-md-12
        %p Content: #{@note.content.html_safe}
        %p Priority: #{@note.priority}
        %p Published_at #{@note.created_at}
        =link_to "All notes", root_path
        =link_to "Edit", edit_note_path(@note)
        =link_to "Delete", note_path(@note), method: :delete
- else 
  .container
    .row
      .col-md-12
        %h1 'Not your Note'
    .row
      .col-md-12
        
        =link_to "All notes", root_path

app/views/welcome/index.html.haml
.container-fluid
  .row
    .col-md-12
      .media.well
        %img.media-object= image_tag "logo.png"
        .media-body
          %h1.media-heading
            YourNoteBook | Leave Your Notes Online

      .jumbotron.well
        %h2
          Lorem Ipsum
        %p
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        %p
          = link_to "Log In", new_user_session_path    

            
      .row
        .col-md-6
          %h2
            Heading
          %p
            Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.

        .col-md-6
          %h2
            Heading
          %p
            Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.